# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8cb520f1c663827989c2ec0c47134f0f4a363ef502a1d89cb39068d1421f06979201af4be90427fbc90690ca96a350ef905c0ae069e28ebaccbcdd810a6b3b5

test:
  secret_key_base: 6a0b78304c6d7b77871d5b4689a1b3494ab65048afa08fe9065a74faace0ddca3a75be4999f8e0219c37fde23633c8c2c03da657c816bbdf97c0c0643f4ea457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
